spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSl=false&serverTimezon=UTC&characterEncoding=utf8
    username: root
    password: "080655"

  #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #前端页面配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: false

 #session登录验证
  security:
    user:
      name: zhanhuiping
      password: 123456
  redis:
    host: localhost  # Redis 服务器地址
    port: 6379        # Redis 端口
    timeout: 6000ms   #超时时间
    lettuce:
      pool:
        max-active: 10   #最大连接数
        max-idle: 5     # 最大空闲连接数
        min-idle: 1     # 最小空闲连接数

  rabbitmq:        #rabbitMQ配置
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10



#错误直接在idea终端以日志的形式显示
logging:
  level:
    org.springframework.security: DEBUG







